### PR TITLE
Change the dockerfile for Tarantool 2.1

### LINKED ISSUE #173: Need to change the dockerfile for alpine 3.5 Tarantool 2.1 version from 2.2 to 1.x

### PR DESCRIPTION
**Pull request by avtikhon**
During bumping alpine from 3.5 to 3.9 at commit:
  aef661e81bc8e7c26f4ac6f516d83a69204653b3 "Bump alpine images version"
    
Found that Tarantool 2.1 branch with version equal and later than 2.1.3
tag didn't build on alpine 3.5 with both dockerfiles available for it,
due to issue:
```
    /usr/src/tarantool/third_party/curl/lib/vtls/openssl.c: In function 'set_ssl_version_min_max':
    /usr/src/tarantool/third_party/curl/lib/vtls/openssl.c:2195:9: error: implicit declaration of function 'SSL_CTX_set_min_proto_version' [-Werror=implicit-function-declaration]
         if(!SSL_CTX_set_min_proto_version(ctx, ossl_ssl_version_min)) {
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /usr/src/tarantool/third_party/curl/lib/vtls/openssl.c:2231:7: error: implicit declaration of function 'SSL_CTX_set_max_proto_version' [-Werror=implicit-function-declaration]
       if(!SSL_CTX_set_max_proto_version(ctx, ossl_ssl_version_max)) {
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /usr/src/tarantool/third_party/curl/lib/url.c: In function 'Curl_connect':
    /usr/src/tarantool/third_party/curl/lib/url.c:1876:13: warning: offset outside bounds of constant string
         hostname++;
         ~~~~~~~~^~
    cc1: some warnings being treated as errors
```

The issue occurred because of the unsupported openssl version, please check [1].
These macros are only available in OpenSSL 1.1.0. While alpine versions uses different openssl versions:
Alpine 3.5: openssl (1.0.2q-r0)
Alpine 3.9: openssl (1.1.1g-r0)

Also in #152 the alpine version was bumped and current change of the
build job for Tarantool 2.1 to use alpine 3.9 resolved the issue.
    
Currently found that on alpine 3.9 it successfully built, but only
with *1.x dockerfile, due to tarantoolctl tool failed installing rocks
at *2.x file.
    
So decided to use for Tarantool 2.1 -> alpine_3.9_1.x dockerfile.
    
Closes #173
Follows up #152

[1] - https://www.openssl.org/docs/man1.1.0/ssl/SSL_CTX_set_max_proto_version.html

### CODE REVIEW

**Comment by Totktonada** [comment]
Is not it fixed with https://github.com/tarantool/tarantool/commit/bc986c9330963329eb71115a82934c6feeea8ce7 ?

**Comment by avtikhon** [comment]
> Is not it fixed with [tarantool/tarantool@bc986c9](https://github.com/tarantool/tarantool/commit/bc986c9330963329eb71115a82934c6feeea8ce7) ?

Seems it didn't help because dockerfiles with alpine 3.5 used it's local curl installation of the 5.59.0 version.
Also about Tarantool versions and the provided fix at bc986c9330963329eb71115a82934c6feeea8ce7:

$ git describe --long bc986c9330963329eb71115a82934c6feeea8ce7
2.1.2-205-gbc986c933

$ git describe --long 2.1.3~1
2.1.2-213-g6a47f1a21

$ git describe --long 2.1.3
2.1.3-0-g38d7d6c5d

**Comment by Totktonada** [comment]
> Seems it didn't help because dockerfiles with alpine 3.5 used it's local curl installation of the 5.59.0 version.

Okay, so it is some another problem (maybe similar).

**Comment by LeonidVas** [comment]
Hi! Thank you for the patch.
i have some questions for you:
* What problem are you solving?
* Why we can't just update libressl on alpine 3.5? Are there any other problems for the build?

I think that copy-pasting the build error into the commit message is not good practice. Please, rewrite it with describing of the problem.

**Comment by avtikhon** [comment]
> Hi! Thank you for the patch.
> i have some questions for you:
> 
> * What problem are you solving?
> * Why we can't just update libressl on alpine 3.5? Are there any other problems for the build?
> 
> I think that copy-pasting the build error into the commit message is not good practice. Please, rewrite it with describing of the problem.

**Comment by LeonidVas** [comment]
> The only problem is to implement the new build of Tarantool 2.1 version which never worked before with this bumped version. This issue was already resolved when tagged 2.1.3 version was build, due to building in both process the same version. Unfortunately in previous build of 2.1.3 was fixed, but 2.1 with the same version was forgotten to fix the same. So solution is to use the same dockerfile for 2.1 as 2.1.3 already uses.

Do I understand correctly that our goal are to build the tarantool 2.1.3+ on an alpine 3.9? (Now it use apine 3.5 - https://hub.docker.com/layers/tarantool/tarantool/2.1.3/images/sha256-d7b3097d611a92ddf73961ebc85ae67730ce3f775fcb878d5eb28b88e57ddd02?context=explore)

**Comment by LeonidVas** [comment]
> You suggest the different solution for fixing 2.1 bumping version, in this way we must update in the same way build of 2.1.3 version to avoid of situation mentioned above.

I try to understand: "Do we want to switch to alpine 3.9 or do we want to build the tarantool 2.1.3+ and update the alpine version because of that?"

**Comment by LeonidVas** [comment]
> That is really hard to hold on control two common comments wrote in different ways.

Sorry, I don't understand what do you mean. My proposal is  to remove the ugly build error (it's not informative in my mind) and insert a human readable description of error about version of libressl or openssl instead.

**Comment by LeonidVas** [comment]
As I can see the libressl is used in alpine 3.5. Is openssl used in alpine 3.9 instead libressl? Why? Why does the commit message use the description of the openssl version for alpine 3.5 when libressl is used for alpine 3.5?

**Comment by LeonidVas** [comment]
If I understand correctly you have 2 problems
* build fail - the openssl/libressl library is the reason
* rocks install fail - the rock installing tool is the reason
If so, your patch only affects the second issue. Or not?

**Comment by LeonidVas** [comment]
From https://github.com/tarantool/tarantool/wiki/Code-review-procedure#commit-message :"Commit message should fit 72 symbols line width...The commit message limit of 72 symbols is not applied when need to copy-paste something long without changes, such as a failed test output...."

**Comment by avtikhon** [comment]
> > The only problem is to implement the new build of Tarantool 2.1 version which never worked before with this bumped version. This issue was already resolved when tagged 2.1.3 version was build, due to building in both process the same version. Unfortunately in previous build of 2.1.3 was fixed, but 2.1 with the same version was forgotten to fix the same. So solution is to use the same dockerfile for 2.1 as 2.1.3 already uses.
> 
> Do I understand correctly that our goal are to build the tarantool 2.1.3+ on an alpine 3.9? (Now it use apine 3.5 - https://hub.docker.com/layers/tarantool/tarantool/2.1.3/images/sha256-d7b3097d611a92ddf73961ebc85ae67730ce3f775fcb878d5eb28b88e57ddd02?context=explore)

Right.

**Comment by avtikhon** [comment]
> > You suggest the different solution for fixing 2.1 bumping version, in this way we must update in the same way build of 2.1.3 version to avoid of situation mentioned above.
> 
> I try to understand: "Do we want to switch to alpine 3.9 or do we want to build the tarantool 2.1.3+ and update the alpine version because of that?"

First of all we need to update the version of alpine 3.9 (#152) and additionally it fixes the current issue

**Comment by avtikhon** [comment]
> > That is really hard to hold on control two common comments wrote in different ways.
> 
> Sorry, I don't understand what do you mean. My proposal is to remove the ugly build error (it's not informative in my mind) and insert a human readable description of error about version of libressl or openssl instead.

@Totktonada always asks me to save the found issue, to be sure in the issue that appeared.

**Comment by avtikhon** [comment]
> > You suggest the different solution for fixing 2.1 bumping version, in this way we must update in the same way build of 2.1.3 version to avoid of situation mentioned above.
> 
> I try to understand: "Do we want to switch to alpine 3.9 or do we want to build the tarantool 2.1.3+ and update the alpine version because of that?"



> As I can see the libressl is used in alpine 3.5. Is openssl used in alpine 3.9 instead libressl? Why? Why does the commit message use the description of the openssl version for alpine 3.5 when libressl is used for alpine 3.5?

Currently there is no dockerfile for 2.1 build, but historically before it was, alpine 3.5 used in there with openssl. For now there is only 3.9 version with openssl exists which before previous its change used 3.5 version.

**Comment by avtikhon** [comment]
> If I understand correctly you have 2 problems
> 
> * build fail - the openssl/libressl library is the reason
> * rocks install fail - the rock installing tool is the reason
>   If so, your patch only affects the second issue. Or not?

This patch fixes only 1st single issue, and avoids of changes for the second issue, that is why it just needs that dockerfile version that uses luacheck instead of tarantoolctl. In the later fixes these dockerfiles will be merged.

**Comment by avtikhon** [comment]
> From https://github.com/tarantool/tarantool/wiki/Code-review-procedure#commit-message :"Commit message should fit 72 symbols line width...The commit message limit of 72 symbols is not applied when need to copy-paste something long without changes, such as a failed test output...."

Actually wanted to make the error mesage more readable - anyway I'll restore its original version.

**Comment by Totktonada** [comment]
There is prose text, which should be limited by 72 symbols and non-prose text (verbatim block), which usually does not. However if it is possible to describe the problem without such verbatim block, the commit message would looks better.

But the idea about keeping error messages remains: it allows to eiasier understand whether another person meet the same problem. In the message above the key information chunk is the error message: "implicit declaration of function 'SSL_CTX_set_min_proto_version'" it can be just placed within a text.

This, however, is not strict requirement, IMHO.

**Comment by LeonidVas** [comment]
> There is prose text, which should be limited by 72 symbols and non-prose text (verbatim block), which usually does not.

For clarity, my comment (72 symbols) was about:
The issue occurred because of the unsupported openssl version, please check [1].
These macros are only available in OpenSSL 1.1.0. While alpine versions uses different openssl versions:

**Comment by avtikhon** [comment]
> > There is prose text, which should be limited by 72 symbols and non-prose text (verbatim block), which usually does not.
> 
> For clarity, my comment (72 symbols) was about:
> The issue occurred because of the unsupported openssl version, please check [1].
> These macros are only available in OpenSSL 1.1.0. While alpine versions uses different openssl versions:

Corrected.

**Comment by LeonidVas** [comment]
> > If I understand correctly you have 2 problems
> > 
> > * build fail - the openssl/libressl library is the reason
> > * rocks install fail - the rock installing tool is the reason
> >   If so, your patch only affects the second issue. Or not?
> 
> This patch fixes only 1st single issue, and avoids of changes for the second issue, that is why it just needs that dockerfile version that uses luarocks instead of tarantoolctl. In the later fixes these dockerfiles will be merged.

After discussion with @avtikhon, I realized that the problem is a missing dockerfile. And the commit message is the background of one of the previous commits. Please, add information about the missing dockerfile to the commit message.

**Comment by avtikhon** [comment]
> > > If I understand correctly you have 2 problems
> > > 
> > > * build fail - the openssl/libressl library is the reason
> > > * rocks install fail - the rock installing tool is the reason
> > >   If so, your patch only affects the second issue. Or not?
> > 
> > 
> > This patch fixes only 1st single issue, and avoids of changes for the second issue, that is why it just needs that dockerfile version that uses luarocks instead of tarantoolctl. In the later fixes these dockerfiles will be merged.
> 
> After discussion with @avtikhon, I realized that the problem is a missing dockerfile. And the commit message is the background of one of the previous commits. Please, add information about the missing dockerfile to the commit message.

Right, added more info in commit message.
